/*!CK:4137149117!*//*1393816575,178179357*/

if (self.CavalryLogger) { CavalryLogger.start_js(["uCtGm"]); }

__d("BoostedPagelikeRefs",[],function(a,b,c,d,e,f){var g={STATUS_TITLE:'status_title',PAGE_NAX:'page_nax',FLUX:'flux',PAGE_COMPETITOR:'page_competitor_editor',PAGE_COMPETITOR_INSIGHTS_LEADERBOARD:'page_competitor_insights_leaderboard'};e.exports=g;});
__d("XUIAmbientNUXTheme",["cx"],function(a,b,c,d,e,f,g){var h={wrapperClassName:"_2x6q",arrowDimensions:{offset:14,length:18}};e.exports=h;});
__d("XUIAmbientNUX.react",["XUIAmbientNUXTheme","ContextualDialog","ContextualDialogArrow","LayerAutoFocus","React","ReactLayer","XUICloseButton.react","cx"],function(a,b,c,d,e,f,g,h,i,j,k,l,m,n){var o=k.PropTypes,p=300,q=380,r=l.createClass({displayName:'XUIAmbientNUX',propTypes:{position:o.oneOf(['above','below','left','right']),alignment:o.oneOf(['left','center','right']),offsetX:o.number,offsetY:o.number,width:o.oneOf(['wide','normal','auto','custom']),customwidth:o.number,shown:o.bool,onCloseButtonClick:o.func},immutableProps:{modal:null},createLayer:function(s){var t=this.getNodeForOwnerRef(this.props.contextRef),u={alignment:this.props.alignment,arrowBehavior:i,context:t,offsetX:this.props.offsetX,offsetY:this.props.offsetY,position:this.props.position,theme:g,width:this.getWidth(this.props)},v=new h(u,s);v.disableBehavior(j);v.conditionShow(this.props.shown);return v;},receiveProps:function(s){var t=this.getNodeForOwnerRef(s.contextRef);this.layer.setContext(t);this.layer.setPosition(s.position).setAlignment(s.alignment).setOffsetX(s.offsetX).setOffsetY(s.offsetY).setWidth(this.getWidth(s)).conditionShow(s.shown);},wrapReactContent:function(s){return (k.DOM.div({className:"_36gm"},m({shade:"light",className:"_36gl",onClick:this.props.onCloseButtonClick}),k.DOM.div({className:"_36gn"},s)));},getWidth:function(s){switch(s.width){case 'wide':return q;case 'custom':return s.customwidth;case 'auto':return null;default:return p;}}});e.exports=r;});
__d("LitestandMicroNux",["AsyncRequest","CSS","ScubaSample","cx"],function(a,b,c,d,e,f,g,h,i,j){var k,l,m,n={show:function(o,p){if(k)return false;if(p)h.addClass(p,"_4_3j");o.show();l=Date.now();k=true;return true;},hide:function(o,p){if(p)h.removeClass(p,"_4_3j");o.hide();o.unsubscribe(m);k=false;},listenClose:function(o,p){m=o.subscribe('hide',p);},log:function(o,p){var q=new i(o,null,{addBrowserFields:true});q.addNormal('response',p);q.addInteger('response_time',Date.now()-l);q.flush();},saveTime:function(o){new g('/ajax/litestand/nux/save_time_property').setData({property:o}).send();}};e.exports=n;});
__d("FollowNuxReminder",["AsyncRequest","DOM","Event","LitestandMicroNux"],function(a,b,c,d,e,f,g,h,i,j){var k,l,m,n,o;function p(){m=h.find(document.body,n);var t=j.show(k,null);if(!t)return;j.listenClose(k,r.bind(null,'clicked_close'));q('follow_nux_ack_time','seen');l=i.listen(m,'click',r.bind(null,'clicked_follow'));}function q(t,u){new g('/ajax/feed/curation/nux_save_time_property').setData({property:t,response:u,token:o}).send();}function r(t){if(!k||!m)return;j.hide(k,m);k=null;m=null;l.remove();q('follow_nux_ack_time',t);}var s={init:function(t,u,v){k=t;n=u;o=v;p();}};e.exports=s;});
__d("PageCompetitorConstants",[],function(a,b,c,d,e,f){var g={MIN_PAGES:5,MAX_PAGES:100};e.exports=g;});